migrate_backdrop.settings:
  type: config_object
  label: 'Migrate Backdrop settings'
  mapping:
    enforce_source_module_tags:
      type: sequence
      label: 'source_module enforcement tags'
      sequence:
        type: string
        label: 'Tag'
    follow_up_migration_tags:
      type: sequence
      label: 'Follow-up migration tags'
      sequence:
        type: string
        label: 'Tag'
